// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type TwobodyFilepath struct {
	RunID     uuid.UUID
	Category  string
	Timestep  int64
	Filename  string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type TwobodyParameter struct {
	Temperature float64
	Density     float64
	Version     string
	RunID       uuid.UUID
	Note        sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
