// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TwobodyFilepath struct {
	Runid     pgtype.UUID
	Category  string
	Timestep  int64
	Filename  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type TwobodyParameter struct {
	Temperature float64
	Density     float64
	Version     string
	Runid       pgtype.UUID
	Note        pgtype.Text
	CreatedAt   pgtype.Timestamp
	UpdatedAt   pgtype.Timestamp
}
