// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: twobody_parameters.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTwoBodyRun = `-- name: CreateTwoBodyRun :one
INSERT INTO twobody_parameters (temperature, density, version, run_id, note, created_at, updated_at)
VALUES(
       $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       $7
      ) RETURNING temperature, density, version, run_id, note, created_at, updated_at
`

type CreateTwoBodyRunParams struct {
	Temperature float64
	Density     float64
	Version     string
	RunID       uuid.UUID
	Note        sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateTwoBodyRun(ctx context.Context, arg CreateTwoBodyRunParams) (TwobodyParameter, error) {
	row := q.db.QueryRowContext(ctx, createTwoBodyRun,
		arg.Temperature,
		arg.Density,
		arg.Version,
		arg.RunID,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TwobodyParameter
	err := row.Scan(
		&i.Temperature,
		&i.Density,
		&i.Version,
		&i.RunID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const removeRunByID = `-- name: RemoveRunByID :one
DELETE FROM twobody_parameters
WHERE run_id = $1
RETURNING temperature, density, version, run_id, note, created_at, updated_at
`

func (q *Queries) RemoveRunByID(ctx context.Context, runID uuid.UUID) (TwobodyParameter, error) {
	row := q.db.QueryRowContext(ctx, removeRunByID, runID)
	var i TwobodyParameter
	err := row.Scan(
		&i.Temperature,
		&i.Density,
		&i.Version,
		&i.RunID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const wipeTwoBodyTable = `-- name: WipeTwoBodyTable :exec
DELETE FROM twobody_parameters
`

func (q *Queries) WipeTwoBodyTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeTwoBodyTable)
	return err
}
