// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: twobody_parameters.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createTwoBodyRun = `-- name: CreateTwoBodyRun :one
INSERT INTO twobody_parameters (temperature, density, version, run_id, note, created_at, updated_at)
VALUES(
       $1,
       $2,
       $3,
       $4,
       $5,
       $6,
       $7
      ) RETURNING temperature, density, version, run_id, note, created_at, updated_at
`

type CreateTwoBodyRunParams struct {
	Temperature float64
	Density     float64
	Version     string
	RunID       uuid.UUID
	Note        sql.NullString
	CreatedAt   time.Time
	UpdatedAt   time.Time
}

func (q *Queries) CreateTwoBodyRun(ctx context.Context, arg CreateTwoBodyRunParams) (TwobodyParameter, error) {
	row := q.db.QueryRowContext(ctx, createTwoBodyRun,
		arg.Temperature,
		arg.Density,
		arg.Version,
		arg.RunID,
		arg.Note,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i TwobodyParameter
	err := row.Scan(
		&i.Temperature,
		&i.Density,
		&i.Version,
		&i.RunID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAllTwoBodyParams = `-- name: ListAllTwoBodyParams :many
SELECT temperature, density, version, run_id, note, created_at, updated_at FROM twobody_parameters
`

func (q *Queries) ListAllTwoBodyParams(ctx context.Context) ([]TwobodyParameter, error) {
	rows, err := q.db.QueryContext(ctx, listAllTwoBodyParams)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TwobodyParameter
	for rows.Next() {
		var i TwobodyParameter
		if err := rows.Scan(
			&i.Temperature,
			&i.Density,
			&i.Version,
			&i.RunID,
			&i.Note,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllTwoBodyRuns = `-- name: ListAllTwoBodyRuns :many
SELECT temperature, density, version, run_id, note FROM twobody_parameters
`

type ListAllTwoBodyRunsRow struct {
	Temperature float64
	Density     float64
	Version     string
	RunID       uuid.UUID
	Note        sql.NullString
}

func (q *Queries) ListAllTwoBodyRuns(ctx context.Context) ([]ListAllTwoBodyRunsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllTwoBodyRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllTwoBodyRunsRow
	for rows.Next() {
		var i ListAllTwoBodyRunsRow
		if err := rows.Scan(
			&i.Temperature,
			&i.Density,
			&i.Version,
			&i.RunID,
			&i.Note,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeRunByID = `-- name: RemoveRunByID :one
DELETE FROM twobody_parameters
WHERE run_id = $1
RETURNING temperature, density, version, run_id, note, created_at, updated_at
`

func (q *Queries) RemoveRunByID(ctx context.Context, runID uuid.UUID) (TwobodyParameter, error) {
	row := q.db.QueryRowContext(ctx, removeRunByID, runID)
	var i TwobodyParameter
	err := row.Scan(
		&i.Temperature,
		&i.Density,
		&i.Version,
		&i.RunID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const selectTwoBodyParamByRunID = `-- name: SelectTwoBodyParamByRunID :one
SELECT temperature, density, version, run_id, note, created_at, updated_at FROM twobody_parameters
WHERE run_id = $1
`

func (q *Queries) SelectTwoBodyParamByRunID(ctx context.Context, runID uuid.UUID) (TwobodyParameter, error) {
	row := q.db.QueryRowContext(ctx, selectTwoBodyParamByRunID, runID)
	var i TwobodyParameter
	err := row.Scan(
		&i.Temperature,
		&i.Density,
		&i.Version,
		&i.RunID,
		&i.Note,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const wipeTwoBodyTable = `-- name: WipeTwoBodyTable :exec
DELETE FROM twobody_parameters
`

func (q *Queries) WipeTwoBodyTable(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, wipeTwoBodyTable)
	return err
}
